<script>
import reuserat from '@/components/entries/reuserat'
import synergy from '@/components/entries/synergy'
import cerner from '@/components/entries/cerner'
import crimsoncrepes from '@/components/entries/crimsoncrepes'
import jmatcher from '@/components/entries/jmatcher'
import schoolprojects from '@/components/entries/schoolprojects'
import library from '@/components/entries/library'
import iot from '@/components/entries/iot'
import kaust from '@/components/entries/kaust'


export default {
        reuserat,
        synergy,
        cerner,
        jmatcher,
        crimsoncrepes,
        schoolprojects,
        library,
        iot,
        kaust
}
</script>
